version: '3.9'
services:
  winner-bot:
    build: .
    container_name: winner-bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./bot/data:/app/bot/data
    restart: unless-stopped
